spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/University
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

  sql:
    init:
      mode: always
  mvc:
    hiddenmethod:
      filter:
        enabled: true

  data:
    web:
      pageable:
        default-page-size: 3
        one-indexed-parameters: true

springdoc:
  api-docs:
    path: /api-docs

university:
  minLectureDurationInMinutes: 30
  maxGroupSize: 10
  startWorkingDay: 6
  endWorkingDay: 22
  maxVacation:
    PROFESSOR: 20
    ASSISTANT: 16
    UNKNOWN: 14
