spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/University
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

  sql:
    init:
      mode: always
  mvc:
    hiddenmethod:
      filter:
        enabled: true

  data:
    web:
      pageable:
        default-page-size: 3
        one-indexed-parameters: true